"""Initial schema.

Enables required extensions and creates all tables from SQLAlchemy metadata.
Creating from metadata keeps this migration DRY and in sync with the models;
subsequent schema changes use autogenerated incremental migrations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-26
"""
from __future__ import annotations

from alembic import op

from app.db.base import Base
import app.models  # noqa: F401

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    # Extensions (also created by infra/postgres init, but safe to repeat).
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
